name: Contract Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install compact
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/download/compact-v0.2.0/compact-installer.sh | sh
          compact update

      - name: Install dependencies
        run: |
          npm install
          cd contract && npm install

      - name: Compile
        run: npm run compact
        working-directory: ./contract

      - name: Run contract tests
        run: npm test
        working-directory: ./contract
